### PR TITLE
feat: added icon for Element

### PR DESCRIPTION
**Pull request by justjanne**
| Icon Name | `element-desktop` | 
| -- | -- |
| File Name | `E/element-desktop.svg` |
| Software | Element (https://element.io/) |

> Please make all pull requests via upstream - not via this soft-fork.

The upstream repository is archived, so this seems to be the only way to add new changes to the icon theme.

### CODE REVIEW

**Comment by fossfreedom** [comment]
@justjanne I just noticed that snwh has marked his repo as a public archive.  Thus there is no longer an upstream.

I'm more than happy for this repo to continue development of this archive theme - I will manage the uploads to Debian & Ubuntu.

To-do so will require a contributor such as yourself with a good eye for detail who can ensure all contributions in future meet the spirit and intent of the snwh original vision.

Would you like to be a contributor with direct access to this repo to help further development?

**Comment by justjanne** [comment]
@fossfreedom in theory I'd love to, but I'm not entirely sure if I'll have enough time. I'll be able to tell in a few weeks whether my schedule allows for this (I'm starting a new job on monday).

**Comment by justjanne** [comment]
@fossfreedom I’ve got the time that’s needed if you’d still like me to assist you in updating this icon theme.

**Comment by fossfreedom** [comment]
@justjanne that would be awesome!

I've sent an invite to you. If you need more rights just shout.  Your PRs to-date are excellent - so feel free to dig around various forks etc / implement your own ideas.  No need to-do PRs yourself - unless you feel you need some feedback or are unsure.

**Pull request merged**
